### ISSUE TITLE
Still  working

### ISSUE THREAD

**Issue by MarcoSuurlant** [flobaader/VisuaLink#1]
Hi is this still working and if so can you give some information how to setup?

**Comment by vavido** [comment]
Most likely not, this was build 5 years ago for Android 4 and has not been maintained since, you can try if it still opens in android studio though. But maybe you were looking for a different repo or project?

**Comment by MarcoSuurlant** [comment]
That’s pity, it opens in Android Studio but don’t build something with the gradle version.
I was looking for something that can read the temperature from Danfoss link cc.

**Comment by vavido** [comment]
In that case the App won't be of much use for you anyway, it can only display a bunch of different images and doesn't use Danfoss link at all.
